repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-yaml
      - id: check-merge-conflict
  - repo: https://gitlab.com/bmares/check-json5
    rev: v1.0.0
    hooks:
      - id: check-json5
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: "v8.24.0"
    hooks:
      - id: eslint
        additional_dependencies:
          - eslint@7.32.0
          - eslint-config-prettier@8.3.0
          - eslint-plugin-libram@0.2.17
        files: \.[jt]sx?$ # *.js, *.jsx, *.ts and *.tsx
        types: [file]
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: "v3.0.0-alpha.0"
    hooks:
      - id: prettier
        additional_dependencies:
          - prettier@2.5.1
