compressionLevel: mixed

enableGlobalCache: false

nodeLinker: node-modules

npmAuthToken: "${NODE_AUTH_TOKEN-xxx}"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"

supportedArchitectures:
  cpu:
    - current
    - x64
  os:
    - current
    - linux

yarnPath: .yarn/releases/yarn-3.6.4.cjs
